### ISSUE TITLE
Since latest update, all text is missing

### ISSUE THREAD

**Issue by zacharyd3** [MarkusMcNugen/docker-qBittorrentvpn#4]
Ever since the latest update, all UI text is missing. The files being downloaded still show but any text (ie. File, Options, tab labels, right click options) are all missing the text and not reading correctly. The downloads still function as they should, but it makes it difficult to see progress on downloads or change any settings.

**Comment by MattDahEpic** [comment]
I was able to restore the text by making the same change as [this commit](https://github.com/MarkusMcNugen/docker-qBittorrentvpn/commit/b096ee553c6bf1beb867ab29bcb8600265689bc8#diff-fedd496f9bcb235f6e3fc6ab9d35a7e6) in my qBittorrent.conf in wherever you set your docker path.

**Comment by zacharyd3** [comment]
Awesome, thanks!
