### ISSUE TITLE
WebUI unavailible if VPN is set to "yes"

### ISSUE THREAD

**Issue by coolcat97** [MarkusMcNugen/docker-qBittorrentvpn#43]
No idea why I'm running into this issue,  but if I enable my VPN with the env argument - 

VPN_ENABLED | no
-- | --

then it works,

however,,,

VPN_ENABLED | yes

does not let the webUI load at all.. no errors in the logs so i'm super confused, is anyone else having this issue as well?

**Comment by coolcat97** [comment]
`2020-03-08 06:59:24.900459 [info] VPN_ENABLED defined as 'no'


2020-03-08 06:59:24.920663 [warn] !!IMPORTANT!! You have set the VPN to disabled, you will NOT be secure!


2020-03-08 06:59:24.941340 [info] Adding 8.8.8.8 to resolv.conf


2020-03-08 06:59:24.963059 [info] Adding 8.8.4.4 to resolv.conf


2020-03-08 06:59:24.982281 [info] PUID not defined. Defaulting to root user


2020-03-08 06:59:25.000637 [info] PGID not defined. Defaulting to root group


root:x:0:0:root:/root:/bin/bash


Group root exists


root:x:0:0:root:/root:/bin/bash


User root exists in /etc/passwd


2020-03-08 06:59:25.024052 [warn] UMASK not defined (via -e UMASK), defaulting to '002'


2020-03-08 06:59:25.042448 [info] Starting qBittorrent daemon...


Logging to /config/qBittorrent/data/logs/qbittorrent-daemon.log.


2020-03-08 06:59:26.075013 [info] Started qBittorrent daemon successfully...


2020-03-08 06:59:26.075040 [info] qBittorrent PID: 52`

**Comment by coolcat97** [comment]
> 
> 
> `2020-03-08 06:59:24.900459 [info] VPN_ENABLED defined as 'no'
> 
> 2020-03-08 06:59:24.920663 [warn] !!IMPORTANT!! You have set the VPN to disabled, you will NOT be secure!
> 
> 2020-03-08 06:59:24.941340 [info] Adding 8.8.8.8 to resolv.conf
> 
> 2020-03-08 06:59:24.963059 [info] Adding 8.8.4.4 to resolv.conf
> 
> 2020-03-08 06:59:24.982281 [info] PUID not defined. Defaulting to root user
> 
> 2020-03-08 06:59:25.000637 [info] PGID not defined. Defaulting to root group
> 
> root❌0:0:root:/root:/bin/bash
> 
> Group root exists
> 
> root❌0:0:root:/root:/bin/bash
> 
> User root exists in /etc/passwd
> 
> 2020-03-08 06:59:25.024052 [warn] UMASK not defined (via -e UMASK), defaulting to '002'
> 
> 2020-03-08 06:59:25.042448 [info] Starting qBittorrent daemon...
> 
> Logging to /config/qBittorrent/data/logs/qbittorrent-daemon.log.
> 
> 2020-03-08 06:59:26.075013 [info] Started qBittorrent daemon successfully...
> 
> 2020-03-08 06:59:26.075040 [info] qBittorrent PID: 52`

working logs

**Comment by coolcat97** [comment]
Non-working logs...

`2020-03-08 07:02:41.442219 [info] VPN_ENABLED defined as 'yes'


2020-03-08 07:02:41.767629 [info] OpenVPN config file (ovpn extension) is located at /config/openvpn/default.ovpn


dos2unix: converting file /config/openvpn/default.ovpn to Unix format...


2020-03-08 07:02:41.935802 [info] VPN remote line defined as 'nnnnnnnnn'


2020-03-08 07:02:41.955150 [info] VPN_REMOTE defined as 'mmmmmmmmmmmmmmm'


2020-03-08 07:02:41.977457 [info] VPN_PORT defined as 'mmmmmmmmmmmmmmm'


2020-03-08 07:02:41.999326 [info] VPN_PROTOCOL defined as 'udp'


2020-03-08 07:02:42.018944 [info] VPN_DEVICE_TYPE defined as 'tun0'


2020-03-08 07:02:42.039581 [info] LAN_NETWORK defined as '192.168.1.0/24'


2020-03-08 07:02:42.061688 [info] NAME_SERVERS defined as '8.8.8.8,8.8.4.4'


2020-03-08 07:02:42.083591 [info] VPN_OPTIONS not defined (via -e VPN_OPTIONS)


2020-03-08 07:02:42.103312 [info] Adding 8.8.8.8 to resolv.conf


2020-03-08 07:02:42.123026 [info] Adding 8.8.4.4 to resolv.conf


2020-03-08 07:02:42.141659 [info] PUID not defined. Defaulting to root user


2020-03-08 07:02:42.160404 [info] PGID not defined. Defaulting to root group


2020-03-08 07:02:42.179884 [info] Starting OpenVPN...


Sun Mar  8 07:02:42 2020 OpenVPN 2.4.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on May 14 2019


Sun Mar  8 07:02:42 2020 library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.08


Sun Mar  8 07:02:42 2020 WARNING: --ns-cert-type is DEPRECATED.  Use --remote-cert-tls instead.


Sun Mar  8 07:02:42 2020 Outgoing Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication


Sun Mar  8 07:02:42 2020 Incoming Control Channel Authentication: Using 160 bit message hash 'SHA1' for HMAC authentication


Sun Mar  8 07:02:42 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.106.123.3:1194


Sun Mar  8 07:02:42 2020 Socket Buffers: R=[212992->212992] S=[212992->212992]


Sun Mar  8 07:02:42 2020 UDP link local: (not bound)


Sun Mar  8 07:02:42 2020 UDP link remote: [AF_INET]185.106.123.3:1194


Sun Mar  8 07:02:42 2020 TLS: Initial packet from [AF_INET]185.106.123.3:1194, sid=1b6873c6 a7d6e57b


Sun Mar  8 07:02:42 2020 VERIFY 


Sun Mar  8 07:02:42 2020 VERIFY OK: nsCertType=SERVER




Sun Mar  8 07:02:43 2020 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA


Sun Mar  8 07:02:43 2020 [server] Peer Connection Initiated with [AF_INET]185.106.123.3:1194


Sun Mar  8 07:02:44 2020 SENT CONTROL [server]: 'PUSH_REQUEST' (status=1)


Sun Mar  8 07:02:44 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway,dhcp-option DNS 10.255.254.1,block-outside-dns,route 10.255.254.1,topology net30,ping 10,ping-restart 120,ifconfig 10.255.254.18 10.255.254.17,peer-id 0,cipher AES-256-GCM'


Sun Mar  8 07:02:44 2020 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:3: block-outside-dns (2.4.4)


Sun Mar  8 07:02:44 2020 OPTIONS IMPORT: timers and/or timeouts modified


Sun Mar  8 07:02:44 2020 OPTIONS IMPORT: --ifconfig/up options modified


Sun Mar  8 07:02:44 2020 OPTIONS IMPORT: route options modified


Sun Mar  8 07:02:44 2020 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified


Sun Mar  8 07:02:44 2020 OPTIONS IMPORT: peer-id set


Sun Mar  8 07:02:44 2020 OPTIONS IMPORT: adjusting link_mtu to 1625


Sun Mar  8 07:02:44 2020 OPTIONS IMPORT: data channel crypto options modified


Sun Mar  8 07:02:44 2020 Data Channel: using negotiated cipher 'AES-256-GCM'


Sun Mar  8 07:02:44 2020 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key


Sun Mar  8 07:02:44 2020 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key


Sun Mar  8 07:02:44 2020 ROUTE_GATEWAY 172.17.0.1/255.255.0.0 IFACE=eth0 HWADDR=02:42:ac:11:00:08


Sun Mar  8 07:02:44 2020 TUN/TAP device tun0 opened


Sun Mar  8 07:02:44 2020 TUN/TAP TX queue length set to 100


Sun Mar  8 07:02:44 2020 do_ifconfig, tt->did_ifconfig_ipv6_setup=0


Sun Mar  8 07:02:44 2020 /sbin/ip link set dev tun0 up mtu 1500


Sun Mar  8 07:02:44 2020 /sbin/ip addr add dev tun0 local 10.255.254.18 peer 10.255.254.17


Sun Mar  8 07:02:44 2020 /sbin/ip route add 185.106.123.3/32 via 172.17.0.1


Sun Mar  8 07:02:44 2020 /sbin/ip route del 0.0.0.0/0


Sun Mar  8 07:02:44 2020 /sbin/ip route add 0.0.0.0/0 via 10.255.254.17


Sun Mar  8 07:02:44 2020 /sbin/ip route add 10.255.254.1/32 via 10.255.254.17


Sun Mar  8 07:02:44 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this


Sun Mar  8 07:02:44 2020 Initialization Sequence Completed


2020-03-08 07:02:47.297165 [info] WebUI port defined as 


2020-03-08 07:02:47.317905 [info] LAN Network defined as 192.168.1.0/24


2020-03-08 07:02:47.349078 [info] Default gateway defined as 10.255.254.17


Error: Nexthop has invalid gateway.


2020-03-08 07:02:47.368010 [info] ip route defined as follows...


--------------------


default via 10.255.254.17 dev tun0 


10.255.254.1 via 10.255.254.17 dev tun0 


10.255.254.17 dev tun0 proto kernel scope link src 10.255.254.18 


172.17.0.0/16 dev eth0 proto kernel scope link src 172.17.0.8 


xxIPxx via 172.17.0.1 dev eth0 


--------------------


2020-03-08 07:02:47.420376 [info] Docker network defined as 172.17.0.0/16


2020-03-08 07:02:47.565154 [info] iptables defined as follows...


--------------------


-P INPUT DROP


-P FORWARD ACCEPT


-P OUTPUT DROP


-A INPUT -i tun0 -j ACCEPT


-A INPUT -s 172.17.0.0/16 -d 172.17.0.0/16 -j ACCEPT


-A INPUT -i eth0 -p udp -m udp --sport 1194 -j ACCEPT


-A INPUT -i eth0 -p tcp -m tcp --dport 8080 -j ACCEPT


-A INPUT -i eth0 -p tcp -m tcp --sport 8080 -j ACCEPT


-A INPUT -s 192.168.1.0/24 -i eth0 -p tcp -m tcp --dport 8999 -j ACCEPT


-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT


-A INPUT -i lo -j ACCEPT


-A OUTPUT -o tun0 -j ACCEPT


-A OUTPUT -s 172.17.0.0/16 -d 172.17.0.0/16 -j ACCEPT


-A OUTPUT -o eth0 -p udp -m udp --dport 1194 -j ACCEPT


-A OUTPUT -o eth0 -p tcp -m tcp --dport 8080 -j ACCEPT


-A OUTPUT -o eth0 -p tcp -m tcp --sport 8080 -j ACCEPT


-A OUTPUT -d 192.168.1.0/24 -o eth0 -p tcp -m tcp --sport 8999 -j ACCEPT


-A OUTPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT


-A OUTPUT -o lo -j ACCEPT


--------------------


root:x:0:0:root:/root:/bin/bash


Group root exists


root:x:0:0:root:/root:/bin/bash


User root exists in /etc/passwd


2020-03-08 07:02:47.687623 [warn] UMASK not defined (via -e UMASK), defaulting to '002'


2020-03-08 07:02:47.705895 [info] Starting qBittorrent daemon...


Logging to /config/qBittorrent/data/logs/qbittorrent-daemon.log.


2020-03-08 07:02:48.760827 [info] Started qBittorrent daemon successfully...


2020-03-08 07:02:48.793728 [info] qBittorrent PID: 178`

**Comment by jaroslawjanas** [comment]
I have the same issue.
The WebUI is not available when **VPN_ENABLED** is set to **yes**

**Comment by royaltongue** [comment]
I get the same error as you when my vpn is turned on, and the same logs as you both on and off, but my WebUI doesn't even load when VPN is set to off.

**Comment by coolcat97** [comment]
Closed

**Comment by coolcat97** [comment]
Closing because it’s the function to not work is not local. VPS is not supported. So I just open an ssh tunnel and use it that way.
