### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by eplusg-zz** [MarkusMcNugen/docker-qBittorrentvpn#71]
Hi,

I have tried to deploy this container several times now and I am getting an error message over and over on boot, can't figure out what I am doing wrong.
This is the only message in the portainer log when the container boots up.

```
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
````

Any tips on what it could be?

**Comment by jjbrunton** [comment]
Are you trying to run this on ARM?

**Comment by eplusg-zz** [comment]
> Are you trying to run this on ARM?

Yeah exactly, that is the problem now when I have read some more about this.
I am trying to run the container on Raspberry Pi 4.

I wasn't aware that containers only work on specific platforms, thought all containers worked everywhere.

Thanks!
