### ISSUE TITLE
Unable to pass other docker through qbittorrentvpn

### ISSUE THREAD

**Issue by SeNeO** [MarkusMcNugen/docker-qBittorrentvpn#8]
I'm trying to connect other docker network through this one using `--network "container:qbittorrentvpbn"`.
The other docker starts fine and I can see in their logs there seems to be working fine, but I can't connect to their webui.
The issue is probably with the default config for the network (iptables?) not allowing connection to the port for the webui for the other docker, (ex: port 9117  for jackett).
Is there anyway to achieve what I want?
I'm running the docker on an Unraid machine, and trying to route at least jackette/sonnar/radarr through this docker.

**Comment by Tr4il** [comment]
You should add the respective ports as exceptions to the iptables script (iptables.sh).

**Comment by SeNeO** [comment]
I've tried to add them via 
`iptables -A INPUT -i eth0 -p tcp --dport 9117 -j ACCEPT`
`iptables -A INPUT -i eth0 -p tcp --sport 9117 -j ACCEPT`
`iptables -A OUTPUT -o eth0 -p tcp --dport 9117 -j ACCEPT`
`iptables -A OUTPUT -o eth0 -p tcp --sport 9117 -j ACCEPT`
(just trying to mimic what I found in iptables.sh, I'm not really familiar with network configs).

I can see the rules via `iptables --list`, but I can't reach Jacket webui.

**Comment by DenisSlobodyanyuk** [comment]
> I've tried to add them via `iptables -A INPUT -i eth0 -p tcp --dport 9117 -j ACCEPT` `iptables -A INPUT -i eth0 -p tcp --sport 9117 -j ACCEPT` `iptables -A OUTPUT -o eth0 -p tcp --dport 9117 -j ACCEPT` `iptables -A OUTPUT -o eth0 -p tcp --sport 9117 -j ACCEPT` (just trying to mimic what I found in iptables.sh, I'm not really familiar with network configs).
> 
> I can see the rules via `iptables --list`, but I can't reach Jacket webui.

Hi. I see you closed this issue, but did not update how you got Jackett to work. I am facing a similar issue.
