### ISSUE TITLE
Add category don't move file

### ISSUE THREAD

**Issue by lavjau** [MarkusMcNugen/docker-qBittorrentvpn#89]
Hi,

I use this container on a Synoogy NAS with Docker and I have a problem with categories: adding a torrent to a category doesn't move it to the chosen folder.
Can you help me?

Thank you for your help.

**Comment by yeahmyusernameis32characterslong** [comment]
Just tried to replicate the issue and I have found the same problem. Set Location option works so the issue isn't Volume related.

**Comment by lavjau** [comment]
Hi,

Adding a torrent in a category works and moves the torrent to the chosen folder.
I didn't make any specific settings to make it work.
I think a restart of the NAS was the solution.
