### ISSUE TITLE
Outdated Docker Hub image

### ISSUE THREAD

**Issue by brogers5** [MarkusMcNugen/docker-qBittorrentvpn#90]
The current image on Docker Hub was built at least 4 months ago and is getting out of date. It's using qBittorrent v4.2.5, which is at least a few releases behind at this point.

Please rebuild and push a new image.

**Comment by StewartThomson** [comment]
For what it's worth you can run 
`apt update && apt install --upgrade-only -y qbittorrent-nox` 
in the container, and then restart the container.

But yeah, the lack of updates is a bit annoying, not sure at what point this is considered abandoned... already missed a major version.

**Comment by brogers5** [comment]
@StewartThomson, I think you meant `--only-upgrade` for the latter command:
```console
root@ad3989a3deda:/# apt install --upgrade-only -y qbittorrent-nox
E: Command line option --upgrade-only is not understood in combination with the other options
```

Nevertheless, this is a decent short-term solution folks should be aware of, assuming rebuilding the image from source isn't an option.

As for whether this is abandoned, I'd say not necessarily. @MarkusMcNugen finally pushed a new image 5 days ago:
https://hub.docker.com/layers/markusmcnugen/qbittorrentvpn/latest/images/sha256-6795b117e1675a0b50a4b6202a2e81ff343f8ababb8355d1d938c5216eaf691d?context=explore

With that said, I still see plenty of unaddressed issues and pull requests, despite @MarkusMcNugen being active on GitHub. It would be nice to see this opened up for co-maintainers to step up. I'd certainly consider throwing my hat into the ring.

**Comment by StewartThomson** [comment]
I ended up switching to https://hub.docker.com/r/binhex/arch-qbittorrentvpn/ 

Transition was almost seamless, just needed some new env variables. Ended up changing to wireguard too, and it's way way faster than openvpn
